---
apiVersion: v1
kind: Service
metadata:
  name: nut-upsd
spec:
  ports:
    - port: 3493
      targetPort: 3493
      name: nut-port
    - port: 5350
      targetPort: 5350
      name: snmp-port
  selector:
    app: nut-upsd